### ISSUE TITLE
how to evaluate code generation task

### ISSUE THREAD

**Issue by gd1m3y** [lvwerra/trl#113]
Hey first of all thankyou for such an amazing framework . I had one question how can i determine a reward model which can decide what reward to give for a code generation task ? or how can i even approach this problem

**Comment by lvwerra** [comment]
You can train a reward model on human preference data (see for example: https://huggingface.co/datasets/openai/summarize_from_feedback) or you could also use a text generation metric as a reward model such as BLEU or ROUGE. However, since the metrics are not perfect there is a chance the model will overfit to those metrics. Does that answer your question?

**Comment by gd1m3y** [comment]
Yeah thankyou for your quick feedback will try this  and yes this answers the question
