### ISSUE TITLE
t5-sentiment.py model_name="lvwerra/t5-imdb" vs google/flan-t5-small question

### ISSUE THREAD

**Issue by gjmulder** [lvwerra/trl#187]
Thanks for the help with getting up to speed with trl. 

I'm trying to baseline with the provided sample sentiment scripts to familiarise myself with trl. Is there any any reason why you're using the model `lvwerra/t5-imdb` and not `google/t5-small`? On HuggingFace there is no model card for `lvwerra/t5-imdb`.

I switched in `google/flan-t5-small` but after training for over eight hours `env/reward_mean` has sat at about -1.0.

**Comment by younesbelkada** [comment]
Hello @gjmulder
Thanks for the issue!

I think there are few things that you need to take into account! 

1- The convergence is usually faster if you pre-train the model in the target domain (here `imdb` generations) - because of the KL-penalty constraining the model to not diverge much from its original domain. If you want your `t5-small` model converge, you might need to tweak [`init_kl_coef`](https://github.com/lvwerra/trl/blob/a05ddbdd836d3217c80a4b3e679ba984bfd4fa24/trl/trainer/ppo_config.py#L37) (make it lower) - TDLR is that in our experiments we preferred to stick on models that has been already pre-trained on `imdb` for faster convergence

2- `google/flan-t5-small` is an instruction-based model, i.e. the model expects instructions as input (in the imdb example something in the lines of `Write a movie review: xxx`. So you need to deal with these models in a specific way. I can imagine that you can tweak the data processing script to add a variety of instructions + tweaking the `init_kl_coef` might help

Let me know if this helps!

**Comment by gjmulder** [comment]
Hi @younesbelkada @lvwerra fantastic advice, tyvm! This is going to help a lot when I start working with my own data.

I'm starting to appreciate that RL adds a new dimension of complexity to training because of all the other hyper-params one needs to gain an intuitive understanding of.
