### ISSUE TITLE
Usage for masked word prediction

### ISSUE THREAD

**Issue by aghanbar** [lvwerra/trl#21]
The examples explain optimizing GPT-2 text generation, but can it be also used to optimize BERT masked token predictions?

**Comment by ozyyshr** [comment]
Hi, thanks for the great work. I also want to know whether and how it can be used for masked token predictions. Thanks in advance!

**Comment by lvwerra** [comment]
Reinforcement learning is designed for sequential decision problems and thus works well for causal language modeling (such as GPT-2). BERT however does not fall in that category since it is a one-shot prediction and not a sequential prediction such as in language modeling. So I don't think it is straight forward to adapt this approach.
