### ISSUE TITLE
Best model checkpointing

### ISSUE THREAD

**Issue by natolambert** [lvwerra/trl#255]
Is it possible to add a config entry to `PPOTrainer` so that it pushes the model to hub whenever the env reward variable is the best it's seen? This helps save the best model in more chaotic training runs.

**Comment by younesbelkada** [comment]
Hello @Bearnardd 
Wow, yes that would be great! Thanks a mile!

**Comment by younesbelkada** [comment]
Let us know if you need any help, we can always assist you

**Comment by Bearnardd** [comment]
Hi @younesbelkada! I had a little bit of time during a weekend to get a grasp of the task and I am wondering if the  argument which controls  whether to push model to the hub if it encounters highest reward should be part of the `PPOConfig` or `PPOTrainer` directly. Secondly, since the rewards are emplaced in the vector, should I check whether the max of this vector is the highest or if the mean is the highest?

**Comment by Bearnardd** [comment]
Hi @younesbelkada @natolambert. I have created a simple [PR](https://github.com/lvwerra/trl/pull/275) with the changes. Feel free to request changes. I have not finished test case yet since I saw that you skip tests that contains pushing stuff to the hub. Nevertheless I will take care of that in thursday.

**Comment by natolambert** [comment]
Completed in #275 
Could also figure out if we can add functionality for `save_pretrained`, but someone can re-open the issue if they want!

**Comment by Piotrekszmel** [comment]
Hi @natolambert. I would like to add this functionality :)

**Comment by natolambert** [comment]
@Piotrekszmel it's been implemented, see #275

**Comment by Piotrekszmel** [comment]
@natolambert I meant `save_pretrained` functionality which You mentioned above.

**Comment by natolambert** [comment]
Why don't you open a PR with what you think this'll look like @Piotrekszmel ?
