### ISSUE TITLE
Adding `DPOTrainer` in trl

### ISSUE THREAD

**Issue by younesbelkada** [lvwerra/trl#405]
DPO (Direct Preference Optimization) is a recent paper from Stanford University: https://arxiv.org/abs/2305.18290 
It could be interesting to implement a generalist trainer that supports this algorithm and provide an example script on how to use it

![Screenshot 2023-06-05 at 18 22 15](https://github.com/lvwerra/trl/assets/49240599/614ca69c-c8b7-4dc3-8dee-fce465e20190)

Anyone on the community is free to start implementing it if they want to help on this! 

cc @natolambert @lewtun @lvwerra @TevenLeScao

**Comment by tomaarsen** [comment]
👍 I'd love to see this

**Comment by mnoukhov** [comment]
I'm looking into it but also waiting on the code. Seems like it could be written on top of RewardTrainer

**Comment by tomaarsen** [comment]
I had a look at this earlier too. The loss is very simple luckily - notable differences with PPO is that the log probs seem to just be a single float per completion, rather than a vector with shape `(response_length,)`.

How the logprobs are computed for the PPO trainer:
https://github.com/lvwerra/trl/blob/fadffc22bce2b52df18310112bcf8f6838a7b2c3/trl/trainer/ppo_trainer.py#L865

**Comment by monksgoyal** [comment]
are you working on DPO to integrate?

**Comment by younesbelkada** [comment]
I believe @kashif and @TevenLeScao are working on it currently, please check #416

**Comment by monksgoyal** [comment]
ok thanks but @kashif i dont see masking in calculating log prob as we should be calculating only on predicted tokens not input/prompt/question tokens and padding tokens.

**Comment by kashif** [comment]
@monksgoyal correct... we wanted to fix up the `Trainer` first and then get the padding aspect done... happy to share the branch with you as well if you want to have a look at the padding?

**Comment by monksgoyal** [comment]
sure will try, i have implemented it myself using huggingface trainer, but i loss has one problem which is written in paper is that loss is decreasing probability of rejected a lot faster than increasing probability of chosen because of log term hence loss needs to be modified a bit. so if you are okay to modify the loss let me know.

**Comment by ssmi153** [comment]
FYI, they’ve now released their code implementation: https://github.com/eric-mitchell/direct-preference-optimization

**Comment by tomaarsen** [comment]
Great job all! I'm looking forward to experimenting with this soon.
