### ISSUE TITLE
[Question] Sign of kl in the reward

### ISSUE THREAD

**Issue by maxjeblick** [lvwerra/trl#463]
First of all, thanks a lot for the amazing implementation!  I have a question regarding the sign of the kullback leibler divergence when calculating the [rewards](https://github.com/lvwerra/trl/blob/0161a8e602d2994a79184e5f4c791ec1afae8640/trl/trainer/ppo_trainer.py#L953).

**First of all, some preliminary observations that helped me to formulate my question:**
1. `rewards` (of shape `(batch_size, num_generated_tokens)`) should be maximized for each token
2. `kl = logprob - ref_logprob` should be minimized (for each token), as it is subtracted from `rewards`
3. `logprob` and `ref_logprob` are calculated by taking the softmax distribution of the rlhf model/ reference model, resp. and computing the log of the distribution at the generated_tokens_ids **of the rlhf model**.

In the literature, e.g.  https://arxiv.org/pdf/1909.08593.pdf, the reward penality is described 
> to keep π from moving too far from ρ, we add a penalty with expectation β KL(π, ρ) 

with π being the rlhf model that is optimized via PPO.

While kullback leibler divergence sounds appealing as a penality term, some people noticed that kl may become negative over time which seems to coincide with deteriorated generation capabilities. 
I interpret this as the softmax distribution of the rlhf model becoming "flatter", i.e. the model is converging to a more uniform token distribution (which should imply  `logprob << -1` ).

**To my question:**
Do you think it makes sense to define the penality as the negative of the L1/L2 distance of `logprob` and `ref_logprob` instead? This should avoid the issue mentioned above, while ensuring that the rlhf model does not "wander off".

**Comment by lvwerra** [comment]
There is a related issues to your question: #486

To your comment regarding smoothed out probability distribution: In that case the model that's been sampled from should still have higher expected probability for the tokens than the reference model. E.g. imagine the active model has a uniform distribution: that would mean that also tokens are selected that are much more unlikely under the reference distribution.

Usually the negative KL issues come from not properly sampling. E.g. tokens that are automatically added such as padding tokens and are not masked out. The active model can assign a very low probability to them since they are not actually sampled causing the KL to drop.

**Comment by maxjeblick** [comment]
Thanks for the detailed answer and referencing to the PR!
