### ISSUE TITLE
Why using LengthSampler to sample max_new_tokens

### ISSUE THREAD

**Issue by wuzheng-sjtu** [lvwerra/trl#498]
Hello! First of all thank you so much for the great work! 
I have a question regarding the StackLlama example. So in the rl_training [example](https://github.com/lvwerra/trl/blob/main/examples/stack_llama/scripts/rl_training.py#L249), the max_new_tokens is sampled via LengthSampler, which is a uniform distribution ranging from min_length and max_length. I'm wondering what is the intuition behind this? I noticed during training the output answer is sometimes cut off (thus not completed) due to a small value of sampled max_new_tokens. Would this affect the PPO training? Let's say if the answer is pretty short, the reward model tends to give a low score for the generated incompleted answer.

Why not just set a fixed max_new_tokens and let the model rollout until tokenizer.eos_token is sampled?

Thanks!

**Comment by lvwerra** [comment]
The length sampler is indeed probably not necessary. Especially in earlier versions we only generated small sequences due to memory constraints and the goal of this was to bring in some variability so the model doesn't learn to just produce `max_new_tokens`. But it should also work without and indeed using the eos token is generally a better idea.

**Comment by wuzheng-sjtu** [comment]
Thank you for the explanation @lvwerra !
