### ISSUE TITLE
StackLLAMA: Reward model training slower and more memory heavy than expected

### ISSUE THREAD

**Issue by jvhoffbauer** [lvwerra/trl#557]
When running the reward model training with a LLAMA 7B model on an  NVIDIA GeForce RTX 3090 with 24GB GPU RAM, one sample takes ~1s and the process consumes 20GB of GPU RAM. I would expect it to be both faster and consume 7GB for the quantized model and a few MB for the LoRA Adapter. I train with a batchsize of 1 for testing. 

Does someone else experience the same? Why is that so?

**Comment by edbeeching** [comment]
Hi, this is probably because during training you also need to store the activations during the forward pass (and optimizer states but that should be small in this setting). To check that the model is quantized and loaded correctly, put a break point after the peft model is loaded and check your memory usage. It should be around 8GB.

**Comment by jvhoffbauer** [comment]
Makes sense. Yes, the model requires only 8GB on load but I understand that storing activations during the (double) forward pass is more memory intensive. 

Thanks for explaining and helping me sanity-check this!
